# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0008_rater_auth_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='submit_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
