# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 20:13
from __future__ import unicode_literals

from django.db import migrations

from movie_lens_online.models import Rater,  Movie,  Rating, Moviegenre
import datetime
import csv


def import_genres(apps, schema_editor):
    Movie = apps.get_model("movie_lens_online", "Movie")
    Moviegenre = apps.get_model("movie_lens_online", "Moviegenre")

    with open ('/Users/David/documents/django-movies/django-movies/Data/u.item', encoding='latin_1') as movie_file:

        movie_dataset = csv.DictReader(movie_file, fieldnames=('movie_id', 'movie_title', 'release_date', 'video release date',
              'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation',
              'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
              'FilmNoir', 'Horror', 'Musical', 'Mystery', 'Romance', 'SciFi',
              'Thriller', 'War', 'Western'), delimiter="|")

        for row in movie_dataset:

            cln_date = datetime.datetime.strptime(row['release_date'], "%d-%b-%Y").date()

            movie_row = Moviegenre(movie=Movie.objects.get(movie_id=row['movie_id']),
                                  unknown=row['unknown'], Action=row['Action'], Adventure=row['Adventure'], Animation=row['Animation'],
                                  Childrens=row['Childrens'], Comedy=row['Comedy'], Crime=row['Crime'], Documentary=row['Documentary'], Drama=row['Drama'],
                                  Fantasy=row['Fantasy'], FilmNoir=row['FilmNoir'], Horror=row['Horror'], Musical=row['Musical'], Mystery=row['Mystery'], Romance=row['Romance'], SciFi=row['SciFi'],
                                  Thriller=row['Thriller'], War=row['War'], Western=row['Western'])
            movie_row.save()





class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0010_moviegenre'),
    ]

    operations = [migrations.RunPython(import_genres)
    ]
