# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 01:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0011_auto_20160509_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.RegexValidator(message='Rating must be 1-5', regex='/^[1-5]$/')]),
        ),
    ]
