# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_lens_online', '0013_auto_20160510_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=255),
        ),
    ]
